### PR TITLE
attester: implement key id generation

### PR DESCRIPTION
**Pull request by 0xDen**
Signed-off-by: Denis Semakin <denis.semakin@3mdeb.com>

### CODE REVIEW

**Comment by 0xDen** [comment]
@arturkow2000 Compiler warning about implicit function is fixed. Also  I do remember  your notes about using not RSA algo. This question is still open and isn't clear. Please review the other parts.

**Review by arturkow2000 — CHANGES_REQUESTED** [review]
@0xDen Once again there is wrong (mixed) indentation. Please configure your editor (if you are using vscode you can configure your workspace to always use the same indentation in all files).
You can add these settings to your config
```json
"editor.tabSize": 4,
"editor.renderWhitespace": "all",
"editor.insertSpaces": true,
```
`renderWhitespace` will show you whether you have space or tab. To convert tabs to spaces you can use vscode built-in function (press CTRL+p and type `Convert indentation`)

Please extend README.md to include information on how to use TPM emulator. These information previously where there but now are gone. Also these instructions are not enough, I tried prieviously to run attester using tpm server without success, `fobnail-attester` connects to server but then fails with
```
ERROR:tcti:src/tss2-tcti/tcti-device.c:439:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpmrm0: No such file or directory 
WARNING:tcti:src/tss2-tcti/tctildr.c:62:tcti_from_init() TCTI init for function 0x7fc982b26fb0 failed with a000a 
WARNING:tcti:src/tss2-tcti/tctildr.c:92:tcti_from_info() Could not initialize TCTI named: tcti-device 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0 
ERROR:tcti:src/tss2-tcti/tcti-device.c:439:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: No such file or directory 
WARNING:tcti:src/tss2-tcti/tctildr.c:62:tcti_from_init() TCTI init for function 0x7fc982b26fb0 failed with a000a 
WARNING:tcti:src/tss2-tcti/tctildr.c:92:tcti_from_info() Could not initialize TCTI named: tcti-device 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0 
WARNING:esys:src/tss2-esys/api/Esys_GetCapability.c:303:Esys_GetCapability_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_GetCapability.c:107:Esys_GetCapability() Esys Finish ErrorCode (0x00000100) 
Error: Esys_GetCapability()
```
On tpm_server I see following logs
```
LIBRARY_COMPATIBILITY_CHECK is ON
Manufacturing NV state...
Size of OBJECT = 2600
Size of components in TPMT_SENSITIVE = 1096
    TPMI_ALG_PUBLIC                 2
    TPM2B_AUTH                      66
    TPM2B_DIGEST                    66
    TPMU_SENSITIVE_COMPOSITE        962
Starting ACT thread...
TPM command server listening on port 2321
Platform server listening on port 2322
Command IPv4 client accepted
Platform IPv4 client accepted
Platform server listening on port 2322
TPM command server listening on port 2321
Command IPv4 client accepted
Platform IPv4 client accepted
Platform server listening on port 2322
TPM command server listening on port 2321
```
I don't have hardware TPM so I can't test `fobnail-attester` functionality.

Please also add `.gitignore` file, and ignore directories with build artifacts, otherwise some day someone accidentally may commit files which he shouldn't.
```
HEAD detached at 15fc051
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.vscode/
	bin/fobnail-attester
	fobnail-attester
	obj/fobnail-attester.o
	obj/tpm2-crypto.o
```

@macpijan Maybe we should introduce `clang-format` so that the code style consistent.
`clang-format` has at least a few predefined styles, also it may be adapted our needs. Vscode C++ extensions supports, so code may be automatically formatted when saving it.

**Comment by 0xDen** [comment]
OMG Again...

**Review by arturkow2000 — APPROVED** [review]

**Comment by 0xDen** [comment]
Merged.

**Pull request merged**
